model_name: 'COCO-Detection//faster_rcnn_R_50_FPN_3x.yaml'
num_workers: 2
ims_per_batch: 3
base_lr: 0.0001
max_iter: 10000
checkpoint_period: 2000
eval_period: 1000
model_weights: '/mnt/c/dev/multimodal-document-processing/experiments/detectron-heimatkunde-layout-analysis/models/detectron2/model_final.pth'
data_dir_test: '/mnt/c/ml-data/heimatkunde-v4'
data_dir_train: '/mnt/c/ml-data/heimatkunde-v4'