model_name: 'COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml'
num_workers: 2
ims_per_batch: 4
base_lr: 0.0001
max_iter: 20000
checkpoint_period: 1000
eval_period: 1000
model_weights: '/mnt/e/ml-models/mask-rcnn/all_classes/model_best.pth'
data_dir_test: '/mnt/c/ml-data/heimatkunde-v4-listings'
data_dir_train: '/mnt/c/ml-data/heimatkunde-v4-listings'